# Generated by Django 5.1.4 on 2024-12-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="default_branch",
            field=models.CharField(default="main", max_length=100),
        ),
        migrations.AddField(
            model_name="repository",
            name="fork",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repository",
            name="full_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="repository",
            name="language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="organization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="pushed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="size",
            field=models.IntegerField(default=0),
        ),
    ]
