# Generated by Django 5.1.4 on 2024-12-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0002_repository_default_branch_repository_fork_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="local_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
