# Generated by Django 5.1.4 on 2024-12-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repos", "0004_windsurfsession"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["updated_at"], name="repos_repos_updated_a26900_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["organization"], name="repos_repos_organiz_a93e4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["language"], name="repos_repos_languag_48bb44_idx"
            ),
        ),
    ]
